#!/bin/bash

M4D_DIR=libMotion4D
TODAY=$(date +'%Y%m%d')

cd ..
zip -r libMotion4D_$TODAY.zip \
$M4D_DIR/CMakeLists.txt \
$M4D_DIR/common.pri \
$M4D_DIR/doxyfile \
$M4D_DIR/m4d.pro \
$M4D_DIR/m4d_sources.pri \
$M4D_DIR/AUTHORS \
$M4D_DIR/README \
$M4D_DIR/COPYING \
$M4D_DIR/NEWS \
$M4D_DIR/libMotion4D.sln \
$M4D_DIR/libMotion4D.vcxproj \
$M4D_DIR/libMotion4D.vcxproj.filters \
$M4D_DIR/m4d.props \
$M4D_DIR/src/m4dGlobalDefs.h \
$M4D_DIR/src/extra/*.cpp \
$M4D_DIR/src/extra/*.h \
$M4D_DIR/src/math/*.cpp \
$M4D_DIR/src/math/*.h \
$M4D_DIR/src/metric/*.cpp \
$M4D_DIR/src/metric/*.h \
$M4D_DIR/src/motion/*.cpp \
$M4D_DIR/src/motion/*.h \
$M4D_DIR/test/testAll.bash \
$M4D_DIR/test/testAll.bat \
$M4D_DIR/test/README.test \
$M4D_DIR/test/tests.pro \
$M4D_DIR/test/calcGeodesic/calcGeodesic.cpp \
$M4D_DIR/test/calcGeodesic/calcGeodesic.pro \
$M4D_DIR/test/calcGeodesic/calcGeodesic.vcxproj \
$M4D_DIR/test/calcGeodesic/calcGeodesic.vcxproj.filters \
$M4D_DIR/test/calcGeodesic/kerr.ini \
$M4D_DIR/test/calcGeodesic/plotGeodesic.gnu \
$M4D_DIR/test/calcParallel/calcParallel.cpp \
$M4D_DIR/test/calcParallel/calcParallel.pro \
$M4D_DIR/test/calcParallel/calcParallel.vcxproj \
$M4D_DIR/test/calcParallel/calcParallel.vcxproj.filters \
$M4D_DIR/test/calcParallel/kerr_timelike.ini \
$M4D_DIR/test/testCircular/testCircular.cpp \
$M4D_DIR/test/testCircular/testCircular.pro \
$M4D_DIR/test/testCircular/testCircular.vcxproj \
$M4D_DIR/test/testCircular/testCircular.vcxproj.filters \
$M4D_DIR/test/testDatabase/testDatabase.cpp \
$M4D_DIR/test/testDatabase/testDatabase.pro \
$M4D_DIR/test/testDatabase/testDatabase.vcxproj \
$M4D_DIR/test/testDatabase/testDatabase.vcxproj.filters \
$M4D_DIR/test/testFWworldline/testFWworldline.cpp \
$M4D_DIR/test/testFWworldline/testFWworldline.pro \
$M4D_DIR/test/testFWworldline/testFWworldline.vcxproj \
$M4D_DIR/test/testFWworldline/testFWworldline.vcxproj.filters \
$M4D_DIR/test/testGeodesic/testGeodesic.cpp \
$M4D_DIR/test/testGeodesic/testGeodesic.pro \
$M4D_DIR/test/testGeodesic/testGeodesic.vcxproj \
$M4D_DIR/test/testGeodesic/testGeodesic.vcxproj.filters \
$M4D_DIR/test/testGeodesic/plotSchwGeods.gnu \
$M4D_DIR/test/testJacobi/testJacobi.cpp \
$M4D_DIR/test/testJacobi/testJacobi.pro \
$M4D_DIR/test/testJacobi/testJacobi.vcxproj \
$M4D_DIR/test/testJacobi/testJacobi.vcxproj.filters \
$M4D_DIR/test/testJacobi/plotJacobi.gnu \
$M4D_DIR/test/testJacobi/kerr_lens.ini \
$M4D_DIR/test/expected_results/m4dTestDB.txt \
$M4D_DIR/test/expected_results/kerr_geod.png \
$M4D_DIR/test/expected_results/points_par.dat \
$M4D_DIR/test/expected_results/points_circ.dat \
$M4D_DIR/test/expected_results/points_fw.dat \
$M4D_DIR/test/expected_results/schw_geods.png \
$M4D_DIR/test/expected_results/kerr_lens.png \
$M4D_DIR/test/expected_results/m4dTestCircular.txt \
$M4D_DIR/sonst/SymPy/alcubierreSimple.py \
$M4D_DIR/sonst/SymPy/barriolaVilenkin.py \
$M4D_DIR/sonst/SymPy/kerr.py \
$M4D_DIR/sonst/SymPy/m4d.py \
$M4D_DIR/sonst/SymPy/schwarzschild.py \
$M4D_DIR/sonst/Maxima/schwarzschild.mac \
$M4D_DIR/sonst/Maple/makeBarriolaVilenkin.mws \
$M4D_DIR/sonst/Maple/makeBonnor.mws \
$M4D_DIR/sonst/Maple/makeKerrBLbardeen.mws \
$M4D_DIR/sonst/Maple/makeKottler.mws  \
$M4D_DIR/sonst/Maple/makeMorrisThorne.mws \
$M4D_DIR/sonst/Maple/makePainleve.mws \
$M4D_DIR/sonst/Maple/makeReissner.mws

cd -

